"""empty message

Revision ID: 259e12606c79
Revises: cc0ce4e84dc9
Create Date: 2024-07-26 01:46:41.502996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259e12606c79'
down_revision = 'cc0ce4e84dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    # ### end Alembic commands ###
