"""Relationships and new artist fields

Revision ID: d0ea88b61985
Revises: 61600f360dc2
Create Date: 2024-07-26 21:25:15.112533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ea88b61985'
down_revision = '61600f360dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=False))
        batch_op.drop_constraint('Artist_state_id_fkey', type_='foreignkey')
        batch_op.drop_column('state_id')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('website_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('Venue_state_id_fkey', type_='foreignkey')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Venue_state_id_fkey', 'State', ['state_id'], ['id'])
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('website_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Artist_state_id_fkey', 'State', ['state_id'], ['id'])
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_venue')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
