"""indexing

Revision ID: de46350148c1
Revises: 059918c19daf
Create Date: 2024-07-29 22:39:16.093326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de46350148c1'
down_revision = '059918c19daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Artist_name'), ['name'], unique=False)

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Show_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Show_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Venue_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Venue_name'))

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Show_venue_id'))
        batch_op.drop_index(batch_op.f('ix_Show_artist_id'))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Artist_name'))

    # ### end Alembic commands ###
